import java.util.Random;
import java.util.Scanner;

public class GuessTheNumberGame {
    private static final Scanner scanner = new Scanner(System.in);
    private static int totalScore = 0;

    public static void main(String[] args) {
        System.out.println("Welcome to the Guess the Number Game!");
        System.out.println("Rules: You will have to guess a number generated by the system within a limited number of attempts.");
        System.out.println("Points are awarded based on how quickly you guess the number.");
        
        boolean playAgain = true;
        while (playAgain) {
            playRound();
            System.out.print("Do you want to play another round? (yes/no): ");
            String response = scanner.nextLine().trim();
            playAgain = response.equalsIgnoreCase("yes");
        }

        System.out.println("Thanks for playing! Your total score is: " + totalScore);
        System.out.println("Goodbye!");
    }

    private static void playRound() {
        Random random = new Random();
        int numberToGuess = random.nextInt(100) + 1; // Random number between 1 and 100
        int attempts = 0;
        int maxAttempts = 10;
        boolean guessedCorrectly = false;

        System.out.println("\n--- New Round ---");
        System.out.println("I have generated a number between 1 and 100. Can you guess it?");
        System.out.println("You have " + maxAttempts + " attempts. Good luck!");

        while (attempts < maxAttempts) {
            System.out.print("Enter your guess: ");
            int userGuess = scanner.nextInt();
            scanner.nextLine(); // Consume newline
            attempts++;

            if (userGuess == numberToGuess) {
                guessedCorrectly = true;
                int points = calculatePoints(attempts);
                totalScore += points;
                System.out.println("Congratulations! You guessed the number in " + attempts + " attempts.");
                System.out.println("You earned " + points + " points in this round.");
                break;
            } else if (userGuess < numberToGuess) {
                System.out.println("Too low! Try again.");
            } else {
                System.out.println("Too high! Try again.");
            }
        }

        if (!guessedCorrectly) {
            System.out.println("Sorry, you've used all " + maxAttempts + " attempts.");
            System.out.println("The correct number was: " + numberToGuess);
        }
    }

    private static int calculatePoints(int attempts) {
        // Award more points for fewer attempts
        if (attempts == 1) return 50;
        else if (attempts <= 3) return 40;
        else if (attempts <= 6) return 30;
        else if (attempts <= 9) return 20;
        else return 10;
    }
}
